// build.rs — generates OUT_DIR/secrets.rs from config/secrets.yaml
// Uses std only (no build-deps). Minimal line-by-line YAML parser.

use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=config/secrets.yaml");

    let yaml_path = PathBuf::from("config/secrets.yaml");
    let yaml = fs::read_to_string(&yaml_path)
        .expect("build.rs: cannot read config/secrets.yaml");

    let patterns = parse_patterns(&yaml);
    let code = emit_rust(&patterns);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(&out_dir).join("secrets.rs");
    fs::write(&out_path, code).expect("build.rs: cannot write secrets.rs");
}

#[derive(Debug, Default)]
struct PatternEntry {
    name: String,
    pattern: String,
    label: String,
    paranoid_only: bool,
}

/// Minimal line-by-line parser for config/secrets.yaml.
/// Handles the specific structure of this file — not a general YAML parser.
fn parse_patterns(yaml: &str) -> Vec<PatternEntry> {
    let mut patterns: Vec<PatternEntry> = Vec::new();
    let mut current: Option<PatternEntry> = None;

    for raw_line in yaml.lines() {
        let line = strip_inline_comment(raw_line);
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if trimmed.starts_with("- name:") {
            if let Some(prev) = current.take() {
                if !prev.name.is_empty() {
                    patterns.push(prev);
                }
            }
            let mut entry = PatternEntry::default();
            entry.name = extract_scalar(trimmed, "- name:").to_string();
            current = Some(entry);
            continue;
        }

        if let Some(ref mut entry) = current {
            if let Some(val) = try_extract(trimmed, "pattern:") {
                entry.pattern = val;
            } else if let Some(val) = try_extract(trimmed, "label:") {
                entry.label = val;
            } else if trimmed.starts_with("paranoid_only:") {
                let val = trimmed.trim_start_matches("paranoid_only:").trim();
                entry.paranoid_only = val == "true";
            }
        }
    }

    if let Some(last) = current {
        if !last.name.is_empty() {
            patterns.push(last);
        }
    }

    patterns
}

/// Strip `# comment` from end of line, but not when inside a single-quoted string.
fn strip_inline_comment(line: &str) -> &str {
    let mut in_quote = false;
    let bytes = line.as_bytes();
    for i in 0..bytes.len() {
        match bytes[i] {
            b'\'' => in_quote = !in_quote,
            b'#' if !in_quote => {
                if i > 0 && bytes[i - 1] == b' ' {
                    return &line[..i];
                }
            }
            _ => {}
        }
    }
    line
}

/// Extract scalar after a key prefix, stripping quotes.
fn extract_scalar<'a>(line: &'a str, prefix: &str) -> &'a str {
    let rest = line[prefix.len()..].trim();
    rest.trim_matches('\'').trim_matches('"')
}

/// Try to extract a value for `key:` from a trimmed line, handling single-quoted strings.
fn try_extract(trimmed: &str, key: &str) -> Option<String> {
    if !trimmed.starts_with(key) {
        return None;
    }
    let rest = trimmed[key.len()..].trim();
    if rest.starts_with('\'') {
        let inner = &rest[1..];
        let mut out = String::new();
        let mut chars = inner.chars().peekable();
        loop {
            match chars.next() {
                None => break,
                Some('\'') => {
                    if chars.peek() == Some(&'\'') {
                        chars.next();
                        out.push('\'');
                    } else {
                        break;
                    }
                }
                Some(c) => out.push(c),
            }
        }
        return Some(out);
    }
    // Double-quoted values: trim wrapping quotes only.
    // Assumption: double-quoted values in config/secrets.yaml do not use \" escapes.
    // The raw content (e.g. \\b) is passed through and double-escaped by emit_rust.
    Some(rest.trim_matches('"').to_string())
}

fn emit_rust(patterns: &[PatternEntry]) -> String {
    let mut out = String::from(
        "// @generated by build.rs from config/secrets.yaml — DO NOT EDIT.\n\
         // Edit config/secrets.yaml and run `cargo build` to regenerate.\n\
         \n\
         pub const SECRET_PATTERN_DEFS: &[SecretPatternDef] = &[\n",
    );

    for p in patterns {
        let pattern_escaped = p.pattern.replace('\\', "\\\\").replace('"', "\\\"");
        let name_escaped = p.name.replace('\\', "\\\\").replace('"', "\\\"");
        let label_escaped = p.label.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!(
            "    SecretPatternDef {{\n        name: \"{name}\",\n        pattern: \"{pattern}\",\n        label: \"{label}\",\n        paranoid_only: {paranoid_only},\n    }},\n",
            name = name_escaped,
            pattern = pattern_escaped,
            label = label_escaped,
            paranoid_only = p.paranoid_only,
        ));
    }

    out.push_str("];\n");
    out
}
