use super::SecretPatternDef;

pub(crate) const SECRET_PATTERN_DEFS: &[SecretPatternDef] = &[
    SecretPatternDef {
        name: "aws_access_key",
        pattern: r"\b(?:A3T[A-Z0-9]|AKIA|ABIA|ACCA|AGPA|AIDA|AIPA|ANPA|ANVA|APKA|AROA|ASCA|ASIA)[A-Z0-9]{16}\b",
        label: "AWS-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "aws_session_token",
        pattern: r"\b(?:FwoGZXIvYXdzE|IQoJb3JpZ2lu)[A-Za-z0-9/+=]+\b",
        label: "AWS-SESSION",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "aws_mws_key",
        pattern: r"\bamzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b",
        label: "AWS-MWS",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "gcp_service_account",
        pattern: r"\b[a-z0-9-]+@[a-z0-9-]+\.iam\.gserviceaccount\.com\b",
        label: "GCP-SERVICE-ACCOUNT",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "google_api_key",
        pattern: r"\bAIza[0-9A-Za-z_-]{35}\b",
        label: "GOOGLE-API",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "google_oauth_id",
        pattern: r"\b[0-9]+-[A-Za-z0-9_]{32}\.apps\.googleusercontent\.com\b",
        label: "GOOGLE-OAUTH",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "google_oauth_secret",
        pattern: r"\bGOCspx-[A-Za-z0-9_-]{28}\b",
        label: "GOOGLE-SECRET",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "azure_storage_key",
        pattern: r"\b[A-Za-z0-9+/]{86}==\b",
        label: "AZURE-STORAGE",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "azure_sas_token",
        pattern: r"\bsig=[A-Za-z0-9%]+&se=[0-9]+&[A-Za-z0-9&=%]+\b",
        label: "AZURE-SAS",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "github_fine_grained",
        pattern: r"\bgithub_pat_[A-Za-z0-9]{22}_[A-Za-z0-9]{59}\b",
        label: "GITHUB-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "github_pat",
        pattern: r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}\b",
        label: "GITHUB-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "gitlab_pat",
        pattern: r"\bglpat-[A-Za-z0-9_-]{20,}\b",
        label: "GITLAB-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "gitlab_pipeline",
        pattern: r"\bglptt-[A-Za-z0-9]{40}\b",
        label: "GITLAB-PIPELINE",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "gitlab_runner",
        pattern: r"\bGR1348941[A-Za-z0-9_-]{20,}\b",
        label: "GITLAB-RUNNER",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "slack_bot_token",
        pattern: r"\bxoxb-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24}\b",
        label: "SLACK-BOT",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "slack_user_token",
        pattern: r"\bxoxp-[0-9]{10,13}-[0-9]{10,13}-[0-9]{10,13}-[a-f0-9]{32}\b",
        label: "SLACK-USER",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "slack_app_token",
        pattern: r"\bxapp-[0-9]-[A-Z0-9]{10,}-[0-9]{10,}-[A-Za-z0-9]{64}\b",
        label: "SLACK-APP",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "slack_webhook",
        pattern: r"https://hooks\.slack\.com/services/T[A-Z0-9]{8,}/B[A-Z0-9]{8,}/[A-Za-z0-9]{24}",
        label: "SLACK-WEBHOOK",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "discord_bot_token",
        pattern: r"\b(?:MTA|MTE|MTI|OT|Nj|Nz|OD)[A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27}\b",
        label: "DISCORD-BOT",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "discord_webhook",
        pattern: r"https://discord(?:app)?\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+",
        label: "DISCORD-WEBHOOK",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "telegram_bot_token",
        pattern: r"\b[0-9]{8,10}:[A-Za-z0-9_-]{35}\b",
        label: "TELEGRAM-BOT",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "stripe_secret_key",
        pattern: r"\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]{24,}\b",
        label: "STRIPE-SECRET",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "stripe_publishable_key",
        pattern: r"\bpk_(?:test|live)_[A-Za-z0-9]{24,}\b",
        label: "STRIPE-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "twilio_api_key",
        pattern: r"\bSK[a-f0-9]{32}\b",
        label: "TWILIO-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "twilio_account_sid",
        pattern: r"\bAC[a-f0-9]{32}\b",
        label: "TWILIO-SID",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "sendgrid_api_key",
        pattern: r"\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b",
        label: "SENDGRID-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "mailchimp_api_key",
        pattern: r"\b[a-f0-9]{32}-us[0-9]{1,2}\b",
        label: "MAILCHIMP-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "mailgun_api_key",
        pattern: r"\bkey-[A-Za-z0-9]{32}\b",
        label: "MAILGUN-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "npm_token",
        pattern: r"\bnpm_[A-Za-z0-9]{36}\b",
        label: "NPM-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "pypi_token",
        pattern: r"\bpypi-[A-Za-z0-9_-]{50,}\b",
        label: "PYPI-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "nuget_api_key",
        pattern: r"\boy2[A-Za-z0-9]{43}\b",
        label: "NUGET-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "heroku_api_key",
        pattern: r"\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b",
        label: "HEROKU-KEY",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "digitalocean_pat",
        pattern: r"\bdop_v1_[a-f0-9]{64}\b",
        label: "DO-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "digitalocean_oauth",
        pattern: r"\bdoo_v1_[a-f0-9]{64}\b",
        label: "DO-OAUTH",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "digitalocean_refresh",
        pattern: r"\bdor_v1_[a-f0-9]{64}\b",
        label: "DO-REFRESH",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "cloudflare_origin_ca",
        pattern: r"\bv1\.0-[a-f0-9]{24}-[a-f0-9]{146}\b",
        label: "CLOUDFLARE-CA",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "sentry_dsn",
        pattern: r"https://[a-f0-9]{32}@[a-z0-9]+\.ingest\.sentry\.io/[0-9]+",
        label: "SENTRY-DSN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "pagerduty_api_key",
        pattern: r"\b[A-Za-z0-9+]{20}\b",
        label: "PAGERDUTY-KEY",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "postgres_uri",
        pattern: r"postgres(?:ql)?://[^:\s]+:[^@\s]+@[^/\s]+/\w+",
        label: "DB-POSTGRES",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "mysql_uri",
        pattern: r"mysql://[^:\s]+:[^@\s]+@[^/\s]+/\w+",
        label: "DB-MYSQL",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "mongodb_uri",
        pattern: r"mongodb(?:\+srv)?://[^:\s]+:[^@\s]+@[^/\s]+",
        label: "DB-MONGODB",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "redis_uri",
        pattern: r"redis://[^:\s]+:[^@\s]+@[^/\s]+",
        label: "DB-REDIS",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "jwt",
        pattern: r"\beyJ[A-Za-z0-9_.+-/=]*\.[A-Za-z0-9_.+-/=]*\.[A-Za-z0-9_.+-/=]*\b",
        label: "JWT",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "private_key_content",
        pattern: r"(?s)-----BEGIN[^-]+-----[A-Za-z0-9+/=\s]+-----END[^-]+-----",
        label: "PRIVATE-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "private_key",
        pattern: r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY(?: BLOCK)?-----",
        label: "PRIVATE-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "ssh_private_key",
        pattern: r"-----BEGIN (?:RSA|DSA|EC|OPENSSH) PRIVATE KEY-----",
        label: "SSH-PRIVATE-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "password_field",
        pattern: r#"\b(?:password|passwd|pwd|secret|secret_key|token|api_key|auth_key|private_key|encryption_key)\b\s*[=:]\s*["']?[^\s"']{8,}["']?"#,
        label: "PASSWORD",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "github_user_url",
        pattern: r"https?://github\.com/([A-Za-z0-9_-]+)(?:/[A-Za-z0-9_.-]+)+",
        label: "GITHUB-URL",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "co_authored_by",
        pattern: r"Co-Authored-By:\s+[A-Z][A-Za-z'-]+ [A-Z][A-Za-z'-]+",
        label: "PII-NAME",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "basic_auth",
        pattern: r"\bBasic\s+[A-Za-z0-9+/]{20,}={0,2}",
        label: "BASIC-AUTH",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "bearer_token",
        pattern: r"\bBearer\s+[A-Za-z0-9_.-]{20,}\b",
        label: "BEARER-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "onepassword_ref",
        pattern: r"\bop://[A-Za-z0-9_-]+(?:/[A-Za-z0-9_.-]+)*\b",
        label: "1PASSWORD-REF",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "onepassword_domain",
        pattern: r"\b[A-Za-z0-9-]+\.1password\.com\b",
        label: "1PASSWORD-DOMAIN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "tailscale_host",
        pattern: r"\b[A-Za-z0-9-]+\.ts\.net\b",
        label: "TAILSCALE-HOST",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "onepassword_service_account",
        pattern: r"\bops_eyJ[A-Za-z0-9_.-]{50,}",
        label: "1PASSWORD-SA-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "bw_session",
        pattern: r"\bBW_SESSION=[A-Za-z0-9+/]{40,}={0,2}",
        label: "BW-SESSION",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "bws_access_token",
        pattern: r"\b0\.[A-Za-z0-9]{20,}\.[A-Za-z0-9]{20,}",
        label: "BWS-TOKEN",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "ssh_public_key",
        pattern: r"ssh-(?:rsa|dss|ed25519|ecdsa)\s+[A-Za-z0-9+/]+={0,2}",
        label: "SSH-PUBLIC-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "anthropic_api_key",
        pattern: r"\bsk-ant-(?:api\d{2}-)?[A-Za-z0-9_-]{32,}\b",
        label: "ANTHROPIC-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "openai_api_key",
        pattern: r"\bsk-(?:proj-)?[A-Za-z0-9_-]{32,}\b",
        label: "OPENAI-KEY",
        paranoid_only: false,
    },
    SecretPatternDef {
        name: "aws_secret_key",
        pattern: r"\b[A-Za-z0-9+/]{40}\b",
        label: "AWS-SECRET",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "datadog_api_key",
        pattern: r"\b[a-f0-9]{32}\b",
        label: "DATADOG-API",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "datadog_app_key",
        pattern: r"\b[a-f0-9]{40}\b",
        label: "DATADOG-APP",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "azure_client_secret",
        pattern: r"\b[A-Za-z0-9~._-]{34}\b",
        label: "AZURE-SECRET",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "twilio_auth_token",
        pattern: r"\b[a-f0-9]{32}\b",
        label: "TWILIO-AUTH",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "base64_secret",
        pattern: r"\b[A-Za-z0-9+/]{40,}={0,2}\b",
        label: "SECRET",
        paranoid_only: true,
    },
    SecretPatternDef {
        name: "cloudflare_api_key",
        pattern: r"\b[A-Za-z0-9_-]{37}\b",
        label: "CLOUDFLARE-KEY",
        paranoid_only: true,
    },
];
